-- Push notification support
-- Run once in Supabase SQL Editor

-- Push subscriptions table
create table if not exists public.push_subscriptions (
  id          bigint generated by default as identity primary key,
  user_id     uuid references auth.users(id) on delete cascade not null,
  endpoint    text not null,
  p256dh      text not null,
  auth        text not null,
  created_at  timestamptz default now() not null,
  unique (user_id, endpoint)
);

alter table public.push_subscriptions enable row level security;

create policy "Users can manage their own subscriptions"
  on public.push_subscriptions
  for all
  using (auth.uid() = user_id);

-- Add reminder_time to profiles
alter table public.profiles
  add column if not exists reminder_time text default '20:00';

-- Index for fast lookup in cron
create index if not exists push_subscriptions_user_id_idx
  on public.push_subscriptions (user_id);
