#!/usr/bin/env python3
"""
Regenerate all BibleQuest mp3 chapters that hit the Edge TTS 10-min cap.

Reads:   /home/appstester0919/split_recipes.json  (produced by probe_long_chapters.py)
For each recipe:
  1. Split verses into upper and lower halves (split index already computed)
  2. Edge TTS gen each half → /tmp/{book}{ch}_upper.mp3 + /tmp/{book}{ch}_lower.mp3
  3. ffmpeg concat (-c copy) → final {book}/{ch}.mp3 (overwrites truncated original)
  4. Probe duration; confirm sum > 600s and both halves < 600s
  5. Log result

Voice rule (must match generate_tts_v2.py):
  - Odd chapter  → zh-HK-HiuGaaiNeural (female)
  - Even chapter → zh-HK-WanLungNeural  (male)
  - Both halves of a split use the same voice (no voice flip mid-chapter)

Idempotent: regenerates the same file each time. Safe to re-run.

Skip詩 119 (already regenerated by regen_psalm_119_split.py, commit 108ac96).
"""
import asyncio
import edge_tts
import subprocess
import json
import os
import sys
from pathlib import Path

RECIPES_PATH = "/home/appstester0919/split_recipes.json"
TEMP_DIR = "/tmp"

# Chapter 119 was already split by regen_psalm_119_split.py — skip it
# to avoid clobbering the working v11 file. If you need to redo it,
# remove this set and the script will regen it the same way.
SKIP_CHAPTERS = {
    ("詩", 119),
}


def probe_duration(path: str) -> float:
    r = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", path],
        capture_output=True, text=True, timeout=10,
    )
    return float(r.stdout.strip())


async def gen_half(text: str, path: str, voice: str, label: str):
    print(f"  [{label}] Edge TTS ({voice}) → {path}", flush=True)
    comm = edge_tts.Communicate(text, voice)
    await comm.save(path)
    size_kb = os.path.getsize(path) / 1024
    d = probe_duration(path)
    print(f"  [{label}] OK {d:.1f}s ({size_kb:.0f} KB)", flush=True)
    return d


def concat_mp3(upper: str, lower: str, final: str):
    list_file = os.path.join(TEMP_DIR, os.path.basename(final) + "_concat.txt")
    with open(list_file, "w") as f:
        f.write(f"file '{upper}'\n")
        f.write(f"file '{lower}'\n")
    cmd = [
        "ffmpeg", "-y", "-f", "concat", "-safe", "0",
        "-i", list_file, "-c", "copy", final,
    ]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        print("[ffmpeg STDERR]", r.stderr[-1000:])
        raise RuntimeError(f"ffmpeg concat failed: rc={r.returncode}")
    os.remove(list_file)


def regen_chapter(recipe: dict) -> dict:
    book = recipe["book_abbr"]
    ch = recipe["chapter"]
    voice = recipe["voice"]
    voice_label = recipe["voice_label"]
    output_path = recipe["output_path"]
    temp_upper = recipe["temp_upper"]
    temp_lower = recipe["temp_lower"]
    split_idx = recipe["split_verse_index"]

    print(f"\n{'='*60}")
    print(f"{recipe['book_name']} {ch} ({voice_label}/{voice})")
    print(f"  verses: {recipe['verse_count']}  split at v{split_idx}  "
          f"upper={recipe['upper_verses']} lower={recipe['lower_verses']}")
    print(f"  current mp3: {recipe['duration_s']}s (likely CUT)")
    print(f"{'='*60}")

    # Load verses
    with open("/mnt/d/AI/BibleQuest2026/public/bible-data.json") as f:
        data = json.load(f)
    verses = data["data"][book][str(ch)]
    assert len(verses) == recipe["verse_count"], \
        f"verse count mismatch: file has {len(verses)}, recipe {recipe['verse_count']}"

    upper_verses = verses[:split_idx]
    lower_verses = verses[split_idx:]
    upper_text = "".join(v[1] for v in upper_verses)
    lower_text = "".join(v[1] for v in lower_verses)
    print(f"  upper text: {len(upper_text)} chars  lower text: {len(lower_text)} chars")

    # Clean stale temp files
    for p in [temp_upper, temp_lower]:
        if os.path.exists(p):
            os.remove(p)

    # Step 1: gen halves
    d_upper = asyncio.run(gen_half(upper_text, temp_upper, voice, "UPPER"))
    d_lower = asyncio.run(gen_half(lower_text, temp_lower, voice, "LOWER"))

    if d_upper >= 600:
        raise RuntimeError(f"  ✗ UPPER half still {d_upper:.1f}s > 600s; split point wrong")
    if d_lower >= 600:
        raise RuntimeError(f"  ✗ LOWER half still {d_lower:.1f}s > 600s; split point wrong")

    # Step 2: concat
    print(f"  [CONCAT] ffmpeg -c copy → {output_path}", flush=True)
    concat_mp3(temp_upper, temp_lower, output_path)

    d_final = probe_duration(output_path)
    size_kb = os.path.getsize(output_path) / 1024
    print(f"  ✓ FINAL: {d_final:.1f}s ({d_final/60:.2f} min)  {size_kb:.0f} KB")
    print(f"    sum of halves: {d_upper + d_lower:.1f}s  (concat may add tiny gap)")

    # Step 3: cleanup temp files
    for p in [temp_upper, temp_lower]:
        if os.path.exists(p):
            os.remove(p)

    return {
        "book": book,
        "chapter": ch,
        "voice": voice,
        "duration_s": round(d_final, 1),
        "size_kb": round(size_kb, 0),
        "upper_s": round(d_upper, 1),
        "lower_s": round(d_lower, 1),
        "status": "ok",
    }


def main():
    with open(RECIPES_PATH) as f:
        recipes = json.load(f)

    # Filter out skip-listed (already regen'd elsewhere)
    pending = [r for r in recipes if (r["book_abbr"], r["chapter"]) not in SKIP_CHAPTERS]
    print(f"Total recipes: {len(recipes)}")
    print(f"Skipping (already done): {len(recipes) - len(pending)}")
    print(f"Pending: {len(pending)}")
    print(f"Estimated time: ~{len(pending) * 4}min (each chapter = 2 Edge TTS calls + concat)")

    results = []
    for i, recipe in enumerate(pending, 1):
        print(f"\n[{i}/{len(pending)}]")
        try:
            r = regen_chapter(recipe)
            results.append(r)
        except Exception as e:
            print(f"  ✗ FAILED: {e}")
            results.append({
                "book": recipe["book_abbr"],
                "chapter": recipe["chapter"],
                "status": "fail",
                "error": str(e),
            })

    # Summary
    print(f"\n\n{'='*60}")
    print(f"REGEN SUMMARY")
    print(f"{'='*60}")
    ok = sum(1 for r in results if r["status"] == "ok")
    fail = len(results) - ok
    print(f"OK: {ok}  FAIL: {fail}")
    for r in results:
        if r["status"] == "ok":
            print(f"  ✓ {r['book']} {r['chapter']}: {r['duration_s']}s "
                  f"(upper={r['upper_s']}s + lower={r['lower_s']}s)")
        else:
            print(f"  ✗ {r['book']} {r['chapter']}: {r.get('error', '?')}")

    # Save results
    out = "/home/appstester0919/split_regen_results.json"
    with open(out, "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    print(f"\nResults saved: {out}")


if __name__ == "__main__":
    main()
